# Generated by Django 5.2.7 on 2025-10-06 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_taskprogress_scheduledscrapejob_scrapejobrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledscrapejob',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scrapejobrun',
            name='scheduled_job',
        ),
        migrations.RemoveField(
            model_name='scrapejobrun',
            name='triggered_by',
        ),
        migrations.DeleteModel(
            name='TaskProgress',
        ),
        migrations.DeleteModel(
            name='ScheduledScrapeJob',
        ),
        migrations.DeleteModel(
            name='ScrapeJobRun',
        ),
    ]
