# Generated by Django 5.2.7 on 2025-10-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name', max_length=100, unique=True)),
                ('source', models.CharField(help_text='Scraper source (indeed, glassdoor, etc.)', max_length=50)),
                ('settings', models.JSONField(default=dict, help_text='JSON configuration for the scraper')),
                ('requests_per_minute', models.PositiveIntegerField(default=10)),
                ('delay_between_requests', models.FloatField(default=2.0, help_text='Seconds to wait between requests')),
                ('use_selenium', models.BooleanField(default=False)),
                ('fetch_descriptions', models.BooleanField(default=True)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scraper Configuration',
                'verbose_name_plural': 'Scraper Configurations',
                'ordering': ['source', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScraperStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('requests_made', models.PositiveIntegerField(default=0)),
                ('successful_requests', models.PositiveIntegerField(default=0)),
                ('failed_requests', models.PositiveIntegerField(default=0)),
                ('jobs_found', models.PositiveIntegerField(default=0)),
                ('jobs_saved', models.PositiveIntegerField(default=0)),
                ('duplicates_skipped', models.PositiveIntegerField(default=0)),
                ('average_response_time', models.FloatField(default=0.0, help_text='Average response time in seconds')),
                ('total_scraping_time', models.FloatField(default=0.0, help_text='Total time spent scraping in seconds')),
                ('error_details', models.JSONField(default=list, help_text='List of errors encountered')),
            ],
            options={
                'verbose_name': 'Scraper Statistics',
                'verbose_name_plural': 'Scraper Statistics',
                'ordering': ['-date', 'source'],
                'unique_together': {('source', 'date')},
            },
        ),
    ]
