# Generated by Django 5.2.7 on 2025-10-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScraperConfiguration',
        ),
        migrations.RemoveField(
            model_name='scraperstats',
            name='average_response_time',
        ),
        migrations.RemoveField(
            model_name='scraperstats',
            name='error_details',
        ),
        migrations.RemoveField(
            model_name='scraperstats',
            name='failed_requests',
        ),
        migrations.RemoveField(
            model_name='scraperstats',
            name='requests_made',
        ),
        migrations.RemoveField(
            model_name='scraperstats',
            name='successful_requests',
        ),
        migrations.AlterField(
            model_name='scraperstats',
            name='source',
            field=models.CharField(help_text='Source: indeed, glassdoor, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='scraperstats',
            name='total_scraping_time',
            field=models.FloatField(default=0.0, help_text='Total time in seconds'),
        ),
    ]
