# Generated by Django 5.2.7 on 2025-10-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_remove_unnecessary_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperstats',
            name='company_enhancements_failed',
            field=models.PositiveIntegerField(default=0, help_text='Jobs that failed enhancement'),
        ),
        migrations.AddField(
            model_name='scraperstats',
            name='company_enhancements_success',
            field=models.PositiveIntegerField(default=0, help_text='Jobs enhanced with company info'),
        ),
        migrations.AddField(
            model_name='scraperstats',
            name='jobs_requested',
            field=models.PositiveIntegerField(default=0, help_text='Number of jobs user requested'),
        ),
        migrations.AddField(
            model_name='scraperstats',
            name='last_url_used',
            field=models.URLField(blank=True, help_text='Last URL scraped for debugging'),
        ),
        migrations.AlterField(
            model_name='scraperstats',
            name='duplicates_skipped',
            field=models.PositiveIntegerField(default=0, help_text='Number of duplicate jobs skipped'),
        ),
        migrations.AlterField(
            model_name='scraperstats',
            name='jobs_found',
            field=models.PositiveIntegerField(default=0, help_text='Number of jobs found on page'),
        ),
        migrations.AlterField(
            model_name='scraperstats',
            name='jobs_saved',
            field=models.PositiveIntegerField(default=0, help_text='Number of jobs successfully saved'),
        ),
        migrations.AlterField(
            model_name='scraperstats',
            name='source',
            field=models.CharField(help_text='Source: indeed, glassdoor, linkedin', max_length=50),
        ),
    ]
